package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppHabitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.habit_id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private Long habitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.comments
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource_type
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.log_date
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource1
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource2
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource3
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource4
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource5
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource6
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource7
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource8
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.resource9
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String resource9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.creator
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.gmt_create
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.modifier
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.gmt_modified
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_log.is_deleted
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.id
     *
     * @return the value of hab_app_habit_log.id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.id
     *
     * @param id the value for hab_app_habit_log.id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.habit_id
     *
     * @return the value of hab_app_habit_log.habit_id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Long getHabitId() {
        return habitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.habit_id
     *
     * @param habitId the value for hab_app_habit_log.habit_id
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setHabitId(Long habitId) {
        this.habitId = habitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.comments
     *
     * @return the value of hab_app_habit_log.comments
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.comments
     *
     * @param comments the value for hab_app_habit_log.comments
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource_type
     *
     * @return the value of hab_app_habit_log.resource_type
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource_type
     *
     * @param resourceType the value for hab_app_habit_log.resource_type
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.log_date
     *
     * @return the value of hab_app_habit_log.log_date
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.log_date
     *
     * @param logDate the value for hab_app_habit_log.log_date
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setLogDate(String logDate) {
        this.logDate = logDate == null ? null : logDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource1
     *
     * @return the value of hab_app_habit_log.resource1
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource1() {
        return resource1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource1
     *
     * @param resource1 the value for hab_app_habit_log.resource1
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource1(String resource1) {
        this.resource1 = resource1 == null ? null : resource1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource2
     *
     * @return the value of hab_app_habit_log.resource2
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource2() {
        return resource2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource2
     *
     * @param resource2 the value for hab_app_habit_log.resource2
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource2(String resource2) {
        this.resource2 = resource2 == null ? null : resource2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource3
     *
     * @return the value of hab_app_habit_log.resource3
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource3() {
        return resource3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource3
     *
     * @param resource3 the value for hab_app_habit_log.resource3
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource3(String resource3) {
        this.resource3 = resource3 == null ? null : resource3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource4
     *
     * @return the value of hab_app_habit_log.resource4
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource4() {
        return resource4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource4
     *
     * @param resource4 the value for hab_app_habit_log.resource4
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource4(String resource4) {
        this.resource4 = resource4 == null ? null : resource4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource5
     *
     * @return the value of hab_app_habit_log.resource5
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource5() {
        return resource5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource5
     *
     * @param resource5 the value for hab_app_habit_log.resource5
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource5(String resource5) {
        this.resource5 = resource5 == null ? null : resource5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource6
     *
     * @return the value of hab_app_habit_log.resource6
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource6() {
        return resource6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource6
     *
     * @param resource6 the value for hab_app_habit_log.resource6
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource6(String resource6) {
        this.resource6 = resource6 == null ? null : resource6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource7
     *
     * @return the value of hab_app_habit_log.resource7
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource7() {
        return resource7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource7
     *
     * @param resource7 the value for hab_app_habit_log.resource7
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource7(String resource7) {
        this.resource7 = resource7 == null ? null : resource7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource8
     *
     * @return the value of hab_app_habit_log.resource8
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource8() {
        return resource8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource8
     *
     * @param resource8 the value for hab_app_habit_log.resource8
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource8(String resource8) {
        this.resource8 = resource8 == null ? null : resource8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.resource9
     *
     * @return the value of hab_app_habit_log.resource9
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getResource9() {
        return resource9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.resource9
     *
     * @param resource9 the value for hab_app_habit_log.resource9
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setResource9(String resource9) {
        this.resource9 = resource9 == null ? null : resource9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.creator
     *
     * @return the value of hab_app_habit_log.creator
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.creator
     *
     * @param creator the value for hab_app_habit_log.creator
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.gmt_create
     *
     * @return the value of hab_app_habit_log.gmt_create
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.gmt_create
     *
     * @param gmtCreate the value for hab_app_habit_log.gmt_create
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.modifier
     *
     * @return the value of hab_app_habit_log.modifier
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.modifier
     *
     * @param modifier the value for hab_app_habit_log.modifier
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.gmt_modified
     *
     * @return the value of hab_app_habit_log.gmt_modified
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.gmt_modified
     *
     * @param gmtModified the value for hab_app_habit_log.gmt_modified
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_log.is_deleted
     *
     * @return the value of hab_app_habit_log.is_deleted
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_log.is_deleted
     *
     * @param isDeleted the value for hab_app_habit_log.is_deleted
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}