package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppHabitTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.id
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.title
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.icon_url
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.icon_color
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String iconColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.description
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.stick_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Integer stickDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.daily_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Integer dailyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.each_time
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Integer eachTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.class1
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Long class1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.class2
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Long class2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.remind
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String remind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.freq_type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String freqType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.freq_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String freqDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.counter
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String counter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.timer
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String timer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.temp_order
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Integer tempOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.used_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Long usedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.creator
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.gmt_create
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.modifier
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.gmt_modified
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template.is_deleted
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.id
     *
     * @return the value of hab_app_habit_template.id
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.id
     *
     * @param id the value for hab_app_habit_template.id
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.title
     *
     * @return the value of hab_app_habit_template.title
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.title
     *
     * @param title the value for hab_app_habit_template.title
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.icon_url
     *
     * @return the value of hab_app_habit_template.icon_url
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.icon_url
     *
     * @param iconUrl the value for hab_app_habit_template.icon_url
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.icon_color
     *
     * @return the value of hab_app_habit_template.icon_color
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getIconColor() {
        return iconColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.icon_color
     *
     * @param iconColor the value for hab_app_habit_template.icon_color
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setIconColor(String iconColor) {
        this.iconColor = iconColor == null ? null : iconColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.description
     *
     * @return the value of hab_app_habit_template.description
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.description
     *
     * @param description the value for hab_app_habit_template.description
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.type
     *
     * @return the value of hab_app_habit_template.type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.type
     *
     * @param type the value for hab_app_habit_template.type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.stick_days
     *
     * @return the value of hab_app_habit_template.stick_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Integer getStickDays() {
        return stickDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.stick_days
     *
     * @param stickDays the value for hab_app_habit_template.stick_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setStickDays(Integer stickDays) {
        this.stickDays = stickDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.daily_count
     *
     * @return the value of hab_app_habit_template.daily_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Integer getDailyCount() {
        return dailyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.daily_count
     *
     * @param dailyCount the value for hab_app_habit_template.daily_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setDailyCount(Integer dailyCount) {
        this.dailyCount = dailyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.each_time
     *
     * @return the value of hab_app_habit_template.each_time
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Integer getEachTime() {
        return eachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.each_time
     *
     * @param eachTime the value for hab_app_habit_template.each_time
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setEachTime(Integer eachTime) {
        this.eachTime = eachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.class1
     *
     * @return the value of hab_app_habit_template.class1
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Long getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.class1
     *
     * @param class1 the value for hab_app_habit_template.class1
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setClass1(Long class1) {
        this.class1 = class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.class2
     *
     * @return the value of hab_app_habit_template.class2
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Long getClass2() {
        return class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.class2
     *
     * @param class2 the value for hab_app_habit_template.class2
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setClass2(Long class2) {
        this.class2 = class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.remind
     *
     * @return the value of hab_app_habit_template.remind
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.remind
     *
     * @param remind the value for hab_app_habit_template.remind
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setRemind(String remind) {
        this.remind = remind == null ? null : remind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.freq_type
     *
     * @return the value of hab_app_habit_template.freq_type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getFreqType() {
        return freqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.freq_type
     *
     * @param freqType the value for hab_app_habit_template.freq_type
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setFreqType(String freqType) {
        this.freqType = freqType == null ? null : freqType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.freq_days
     *
     * @return the value of hab_app_habit_template.freq_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getFreqDays() {
        return freqDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.freq_days
     *
     * @param freqDays the value for hab_app_habit_template.freq_days
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setFreqDays(String freqDays) {
        this.freqDays = freqDays == null ? null : freqDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.counter
     *
     * @return the value of hab_app_habit_template.counter
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.counter
     *
     * @param counter the value for hab_app_habit_template.counter
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setCounter(String counter) {
        this.counter = counter == null ? null : counter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.timer
     *
     * @return the value of hab_app_habit_template.timer
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getTimer() {
        return timer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.timer
     *
     * @param timer the value for hab_app_habit_template.timer
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setTimer(String timer) {
        this.timer = timer == null ? null : timer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.temp_order
     *
     * @return the value of hab_app_habit_template.temp_order
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Integer getTempOrder() {
        return tempOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.temp_order
     *
     * @param tempOrder the value for hab_app_habit_template.temp_order
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setTempOrder(Integer tempOrder) {
        this.tempOrder = tempOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.used_count
     *
     * @return the value of hab_app_habit_template.used_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Long getUsedCount() {
        return usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.used_count
     *
     * @param usedCount the value for hab_app_habit_template.used_count
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setUsedCount(Long usedCount) {
        this.usedCount = usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.creator
     *
     * @return the value of hab_app_habit_template.creator
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.creator
     *
     * @param creator the value for hab_app_habit_template.creator
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.gmt_create
     *
     * @return the value of hab_app_habit_template.gmt_create
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.gmt_create
     *
     * @param gmtCreate the value for hab_app_habit_template.gmt_create
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.modifier
     *
     * @return the value of hab_app_habit_template.modifier
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.modifier
     *
     * @param modifier the value for hab_app_habit_template.modifier
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.gmt_modified
     *
     * @return the value of hab_app_habit_template.gmt_modified
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.gmt_modified
     *
     * @param gmtModified the value for hab_app_habit_template.gmt_modified
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template.is_deleted
     *
     * @return the value of hab_app_habit_template.is_deleted
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template.is_deleted
     *
     * @param isDeleted the value for hab_app_habit_template.is_deleted
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}