package com.letsup.habit.app.backend.dao.entity;

import com.alibaba.rock.dal.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HabAppHabitLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected Page page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected String fullOrgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public HabAppHabitLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public Page getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setFullOrgPath(String fullOrgPath) {
        this.fullOrgPath=fullOrgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getFullOrgPath() {
        return fullOrgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public void setOwner(String owner) {
        this.owner=owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHabitIdIsNull() {
            addCriterion("habit_id is null");
            return (Criteria) this;
        }

        public Criteria andHabitIdIsNotNull() {
            addCriterion("habit_id is not null");
            return (Criteria) this;
        }

        public Criteria andHabitIdEqualTo(Long value) {
            addCriterion("habit_id =", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotEqualTo(Long value) {
            addCriterion("habit_id <>", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdGreaterThan(Long value) {
            addCriterion("habit_id >", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdGreaterThanOrEqualTo(Long value) {
            addCriterion("habit_id >=", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdLessThan(Long value) {
            addCriterion("habit_id <", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdLessThanOrEqualTo(Long value) {
            addCriterion("habit_id <=", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdIn(List<Long> values) {
            addCriterion("habit_id in", values, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotIn(List<Long> values) {
            addCriterion("habit_id not in", values, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdBetween(Long value1, Long value2) {
            addCriterion("habit_id between", value1, value2, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotBetween(Long value1, Long value2) {
            addCriterion("habit_id not between", value1, value2, "habitId");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("resource_type is null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("resource_type is not null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("resource_type =", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("resource_type <>", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("resource_type >", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("resource_type >=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("resource_type <", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("resource_type <=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLike(String value) {
            addCriterion("resource_type like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("resource_type not like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIn(List<String> values) {
            addCriterion("resource_type in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotIn(List<String> values) {
            addCriterion("resource_type not in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("resource_type between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("resource_type not between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNull() {
            addCriterion("log_date is null");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNotNull() {
            addCriterion("log_date is not null");
            return (Criteria) this;
        }

        public Criteria andLogDateEqualTo(String value) {
            addCriterion("log_date =", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotEqualTo(String value) {
            addCriterion("log_date <>", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThan(String value) {
            addCriterion("log_date >", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThanOrEqualTo(String value) {
            addCriterion("log_date >=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThan(String value) {
            addCriterion("log_date <", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThanOrEqualTo(String value) {
            addCriterion("log_date <=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLike(String value) {
            addCriterion("log_date like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotLike(String value) {
            addCriterion("log_date not like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateIn(List<String> values) {
            addCriterion("log_date in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotIn(List<String> values) {
            addCriterion("log_date not in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateBetween(String value1, String value2) {
            addCriterion("log_date between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotBetween(String value1, String value2) {
            addCriterion("log_date not between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andResource1IsNull() {
            addCriterion("resource1 is null");
            return (Criteria) this;
        }

        public Criteria andResource1IsNotNull() {
            addCriterion("resource1 is not null");
            return (Criteria) this;
        }

        public Criteria andResource1EqualTo(String value) {
            addCriterion("resource1 =", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1NotEqualTo(String value) {
            addCriterion("resource1 <>", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1GreaterThan(String value) {
            addCriterion("resource1 >", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1GreaterThanOrEqualTo(String value) {
            addCriterion("resource1 >=", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1LessThan(String value) {
            addCriterion("resource1 <", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1LessThanOrEqualTo(String value) {
            addCriterion("resource1 <=", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1Like(String value) {
            addCriterion("resource1 like", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1NotLike(String value) {
            addCriterion("resource1 not like", value, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1In(List<String> values) {
            addCriterion("resource1 in", values, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1NotIn(List<String> values) {
            addCriterion("resource1 not in", values, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1Between(String value1, String value2) {
            addCriterion("resource1 between", value1, value2, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource1NotBetween(String value1, String value2) {
            addCriterion("resource1 not between", value1, value2, "resource1");
            return (Criteria) this;
        }

        public Criteria andResource2IsNull() {
            addCriterion("resource2 is null");
            return (Criteria) this;
        }

        public Criteria andResource2IsNotNull() {
            addCriterion("resource2 is not null");
            return (Criteria) this;
        }

        public Criteria andResource2EqualTo(String value) {
            addCriterion("resource2 =", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2NotEqualTo(String value) {
            addCriterion("resource2 <>", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2GreaterThan(String value) {
            addCriterion("resource2 >", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2GreaterThanOrEqualTo(String value) {
            addCriterion("resource2 >=", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2LessThan(String value) {
            addCriterion("resource2 <", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2LessThanOrEqualTo(String value) {
            addCriterion("resource2 <=", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2Like(String value) {
            addCriterion("resource2 like", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2NotLike(String value) {
            addCriterion("resource2 not like", value, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2In(List<String> values) {
            addCriterion("resource2 in", values, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2NotIn(List<String> values) {
            addCriterion("resource2 not in", values, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2Between(String value1, String value2) {
            addCriterion("resource2 between", value1, value2, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource2NotBetween(String value1, String value2) {
            addCriterion("resource2 not between", value1, value2, "resource2");
            return (Criteria) this;
        }

        public Criteria andResource3IsNull() {
            addCriterion("resource3 is null");
            return (Criteria) this;
        }

        public Criteria andResource3IsNotNull() {
            addCriterion("resource3 is not null");
            return (Criteria) this;
        }

        public Criteria andResource3EqualTo(String value) {
            addCriterion("resource3 =", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3NotEqualTo(String value) {
            addCriterion("resource3 <>", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3GreaterThan(String value) {
            addCriterion("resource3 >", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3GreaterThanOrEqualTo(String value) {
            addCriterion("resource3 >=", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3LessThan(String value) {
            addCriterion("resource3 <", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3LessThanOrEqualTo(String value) {
            addCriterion("resource3 <=", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3Like(String value) {
            addCriterion("resource3 like", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3NotLike(String value) {
            addCriterion("resource3 not like", value, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3In(List<String> values) {
            addCriterion("resource3 in", values, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3NotIn(List<String> values) {
            addCriterion("resource3 not in", values, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3Between(String value1, String value2) {
            addCriterion("resource3 between", value1, value2, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource3NotBetween(String value1, String value2) {
            addCriterion("resource3 not between", value1, value2, "resource3");
            return (Criteria) this;
        }

        public Criteria andResource4IsNull() {
            addCriterion("resource4 is null");
            return (Criteria) this;
        }

        public Criteria andResource4IsNotNull() {
            addCriterion("resource4 is not null");
            return (Criteria) this;
        }

        public Criteria andResource4EqualTo(String value) {
            addCriterion("resource4 =", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4NotEqualTo(String value) {
            addCriterion("resource4 <>", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4GreaterThan(String value) {
            addCriterion("resource4 >", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4GreaterThanOrEqualTo(String value) {
            addCriterion("resource4 >=", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4LessThan(String value) {
            addCriterion("resource4 <", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4LessThanOrEqualTo(String value) {
            addCriterion("resource4 <=", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4Like(String value) {
            addCriterion("resource4 like", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4NotLike(String value) {
            addCriterion("resource4 not like", value, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4In(List<String> values) {
            addCriterion("resource4 in", values, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4NotIn(List<String> values) {
            addCriterion("resource4 not in", values, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4Between(String value1, String value2) {
            addCriterion("resource4 between", value1, value2, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource4NotBetween(String value1, String value2) {
            addCriterion("resource4 not between", value1, value2, "resource4");
            return (Criteria) this;
        }

        public Criteria andResource5IsNull() {
            addCriterion("resource5 is null");
            return (Criteria) this;
        }

        public Criteria andResource5IsNotNull() {
            addCriterion("resource5 is not null");
            return (Criteria) this;
        }

        public Criteria andResource5EqualTo(String value) {
            addCriterion("resource5 =", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5NotEqualTo(String value) {
            addCriterion("resource5 <>", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5GreaterThan(String value) {
            addCriterion("resource5 >", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5GreaterThanOrEqualTo(String value) {
            addCriterion("resource5 >=", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5LessThan(String value) {
            addCriterion("resource5 <", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5LessThanOrEqualTo(String value) {
            addCriterion("resource5 <=", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5Like(String value) {
            addCriterion("resource5 like", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5NotLike(String value) {
            addCriterion("resource5 not like", value, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5In(List<String> values) {
            addCriterion("resource5 in", values, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5NotIn(List<String> values) {
            addCriterion("resource5 not in", values, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5Between(String value1, String value2) {
            addCriterion("resource5 between", value1, value2, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource5NotBetween(String value1, String value2) {
            addCriterion("resource5 not between", value1, value2, "resource5");
            return (Criteria) this;
        }

        public Criteria andResource6IsNull() {
            addCriterion("resource6 is null");
            return (Criteria) this;
        }

        public Criteria andResource6IsNotNull() {
            addCriterion("resource6 is not null");
            return (Criteria) this;
        }

        public Criteria andResource6EqualTo(String value) {
            addCriterion("resource6 =", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6NotEqualTo(String value) {
            addCriterion("resource6 <>", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6GreaterThan(String value) {
            addCriterion("resource6 >", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6GreaterThanOrEqualTo(String value) {
            addCriterion("resource6 >=", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6LessThan(String value) {
            addCriterion("resource6 <", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6LessThanOrEqualTo(String value) {
            addCriterion("resource6 <=", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6Like(String value) {
            addCriterion("resource6 like", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6NotLike(String value) {
            addCriterion("resource6 not like", value, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6In(List<String> values) {
            addCriterion("resource6 in", values, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6NotIn(List<String> values) {
            addCriterion("resource6 not in", values, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6Between(String value1, String value2) {
            addCriterion("resource6 between", value1, value2, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource6NotBetween(String value1, String value2) {
            addCriterion("resource6 not between", value1, value2, "resource6");
            return (Criteria) this;
        }

        public Criteria andResource7IsNull() {
            addCriterion("resource7 is null");
            return (Criteria) this;
        }

        public Criteria andResource7IsNotNull() {
            addCriterion("resource7 is not null");
            return (Criteria) this;
        }

        public Criteria andResource7EqualTo(String value) {
            addCriterion("resource7 =", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7NotEqualTo(String value) {
            addCriterion("resource7 <>", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7GreaterThan(String value) {
            addCriterion("resource7 >", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7GreaterThanOrEqualTo(String value) {
            addCriterion("resource7 >=", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7LessThan(String value) {
            addCriterion("resource7 <", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7LessThanOrEqualTo(String value) {
            addCriterion("resource7 <=", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7Like(String value) {
            addCriterion("resource7 like", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7NotLike(String value) {
            addCriterion("resource7 not like", value, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7In(List<String> values) {
            addCriterion("resource7 in", values, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7NotIn(List<String> values) {
            addCriterion("resource7 not in", values, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7Between(String value1, String value2) {
            addCriterion("resource7 between", value1, value2, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource7NotBetween(String value1, String value2) {
            addCriterion("resource7 not between", value1, value2, "resource7");
            return (Criteria) this;
        }

        public Criteria andResource8IsNull() {
            addCriterion("resource8 is null");
            return (Criteria) this;
        }

        public Criteria andResource8IsNotNull() {
            addCriterion("resource8 is not null");
            return (Criteria) this;
        }

        public Criteria andResource8EqualTo(String value) {
            addCriterion("resource8 =", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8NotEqualTo(String value) {
            addCriterion("resource8 <>", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8GreaterThan(String value) {
            addCriterion("resource8 >", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8GreaterThanOrEqualTo(String value) {
            addCriterion("resource8 >=", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8LessThan(String value) {
            addCriterion("resource8 <", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8LessThanOrEqualTo(String value) {
            addCriterion("resource8 <=", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8Like(String value) {
            addCriterion("resource8 like", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8NotLike(String value) {
            addCriterion("resource8 not like", value, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8In(List<String> values) {
            addCriterion("resource8 in", values, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8NotIn(List<String> values) {
            addCriterion("resource8 not in", values, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8Between(String value1, String value2) {
            addCriterion("resource8 between", value1, value2, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource8NotBetween(String value1, String value2) {
            addCriterion("resource8 not between", value1, value2, "resource8");
            return (Criteria) this;
        }

        public Criteria andResource9IsNull() {
            addCriterion("resource9 is null");
            return (Criteria) this;
        }

        public Criteria andResource9IsNotNull() {
            addCriterion("resource9 is not null");
            return (Criteria) this;
        }

        public Criteria andResource9EqualTo(String value) {
            addCriterion("resource9 =", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9NotEqualTo(String value) {
            addCriterion("resource9 <>", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9GreaterThan(String value) {
            addCriterion("resource9 >", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9GreaterThanOrEqualTo(String value) {
            addCriterion("resource9 >=", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9LessThan(String value) {
            addCriterion("resource9 <", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9LessThanOrEqualTo(String value) {
            addCriterion("resource9 <=", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9Like(String value) {
            addCriterion("resource9 like", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9NotLike(String value) {
            addCriterion("resource9 not like", value, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9In(List<String> values) {
            addCriterion("resource9 in", values, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9NotIn(List<String> values) {
            addCriterion("resource9 not in", values, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9Between(String value1, String value2) {
            addCriterion("resource9 between", value1, value2, "resource9");
            return (Criteria) this;
        }

        public Criteria andResource9NotBetween(String value1, String value2) {
            addCriterion("resource9 not between", value1, value2, "resource9");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 03 11:13:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}