package com.letsup.habit.app.backend.dao.entity;

import com.alibaba.rock.dal.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HabAppHabitDailyRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected Page page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected String fullOrgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public HabAppHabitDailyRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public Page getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void setFullOrgPath(String fullOrgPath) {
        this.fullOrgPath=fullOrgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public String getFullOrgPath() {
        return fullOrgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public void setOwner(String owner) {
        this.owner=owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHabitIdIsNull() {
            addCriterion("habit_id is null");
            return (Criteria) this;
        }

        public Criteria andHabitIdIsNotNull() {
            addCriterion("habit_id is not null");
            return (Criteria) this;
        }

        public Criteria andHabitIdEqualTo(Long value) {
            addCriterion("habit_id =", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotEqualTo(Long value) {
            addCriterion("habit_id <>", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdGreaterThan(Long value) {
            addCriterion("habit_id >", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdGreaterThanOrEqualTo(Long value) {
            addCriterion("habit_id >=", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdLessThan(Long value) {
            addCriterion("habit_id <", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdLessThanOrEqualTo(Long value) {
            addCriterion("habit_id <=", value, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdIn(List<Long> values) {
            addCriterion("habit_id in", values, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotIn(List<Long> values) {
            addCriterion("habit_id not in", values, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdBetween(Long value1, Long value2) {
            addCriterion("habit_id between", value1, value2, "habitId");
            return (Criteria) this;
        }

        public Criteria andHabitIdNotBetween(Long value1, Long value2) {
            addCriterion("habit_id not between", value1, value2, "habitId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdIsNull() {
            addCriterion("family_id is null");
            return (Criteria) this;
        }

        public Criteria andFamilyIdIsNotNull() {
            addCriterion("family_id is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyIdEqualTo(Long value) {
            addCriterion("family_id =", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdNotEqualTo(Long value) {
            addCriterion("family_id <>", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdGreaterThan(Long value) {
            addCriterion("family_id >", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("family_id >=", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdLessThan(Long value) {
            addCriterion("family_id <", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdLessThanOrEqualTo(Long value) {
            addCriterion("family_id <=", value, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdIn(List<Long> values) {
            addCriterion("family_id in", values, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdNotIn(List<Long> values) {
            addCriterion("family_id not in", values, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdBetween(Long value1, Long value2) {
            addCriterion("family_id between", value1, value2, "familyId");
            return (Criteria) this;
        }

        public Criteria andFamilyIdNotBetween(Long value1, Long value2) {
            addCriterion("family_id not between", value1, value2, "familyId");
            return (Criteria) this;
        }

        public Criteria andExecutorIsNull() {
            addCriterion("executor is null");
            return (Criteria) this;
        }

        public Criteria andExecutorIsNotNull() {
            addCriterion("executor is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorEqualTo(Long value) {
            addCriterion("executor =", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotEqualTo(Long value) {
            addCriterion("executor <>", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorGreaterThan(Long value) {
            addCriterion("executor >", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorGreaterThanOrEqualTo(Long value) {
            addCriterion("executor >=", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorLessThan(Long value) {
            addCriterion("executor <", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorLessThanOrEqualTo(Long value) {
            addCriterion("executor <=", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorIn(List<Long> values) {
            addCriterion("executor in", values, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotIn(List<Long> values) {
            addCriterion("executor not in", values, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorBetween(Long value1, Long value2) {
            addCriterion("executor between", value1, value2, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotBetween(Long value1, Long value2) {
            addCriterion("executor not between", value1, value2, "executor");
            return (Criteria) this;
        }

        public Criteria andIsStickedIsNull() {
            addCriterion("is_sticked is null");
            return (Criteria) this;
        }

        public Criteria andIsStickedIsNotNull() {
            addCriterion("is_sticked is not null");
            return (Criteria) this;
        }

        public Criteria andIsStickedEqualTo(String value) {
            addCriterion("is_sticked =", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedNotEqualTo(String value) {
            addCriterion("is_sticked <>", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedGreaterThan(String value) {
            addCriterion("is_sticked >", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedGreaterThanOrEqualTo(String value) {
            addCriterion("is_sticked >=", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedLessThan(String value) {
            addCriterion("is_sticked <", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedLessThanOrEqualTo(String value) {
            addCriterion("is_sticked <=", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedLike(String value) {
            addCriterion("is_sticked like", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedNotLike(String value) {
            addCriterion("is_sticked not like", value, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedIn(List<String> values) {
            addCriterion("is_sticked in", values, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedNotIn(List<String> values) {
            addCriterion("is_sticked not in", values, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedBetween(String value1, String value2) {
            addCriterion("is_sticked between", value1, value2, "isSticked");
            return (Criteria) this;
        }

        public Criteria andIsStickedNotBetween(String value1, String value2) {
            addCriterion("is_sticked not between", value1, value2, "isSticked");
            return (Criteria) this;
        }

        public Criteria andBonusIsNull() {
            addCriterion("bonus is null");
            return (Criteria) this;
        }

        public Criteria andBonusIsNotNull() {
            addCriterion("bonus is not null");
            return (Criteria) this;
        }

        public Criteria andBonusEqualTo(Integer value) {
            addCriterion("bonus =", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotEqualTo(Integer value) {
            addCriterion("bonus <>", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThan(Integer value) {
            addCriterion("bonus >", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus >=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThan(Integer value) {
            addCriterion("bonus <", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThanOrEqualTo(Integer value) {
            addCriterion("bonus <=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusIn(List<Integer> values) {
            addCriterion("bonus in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotIn(List<Integer> values) {
            addCriterion("bonus not in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusBetween(Integer value1, Integer value2) {
            addCriterion("bonus between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus not between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andHasLogIsNull() {
            addCriterion("has_log is null");
            return (Criteria) this;
        }

        public Criteria andHasLogIsNotNull() {
            addCriterion("has_log is not null");
            return (Criteria) this;
        }

        public Criteria andHasLogEqualTo(String value) {
            addCriterion("has_log =", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogNotEqualTo(String value) {
            addCriterion("has_log <>", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogGreaterThan(String value) {
            addCriterion("has_log >", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogGreaterThanOrEqualTo(String value) {
            addCriterion("has_log >=", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogLessThan(String value) {
            addCriterion("has_log <", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogLessThanOrEqualTo(String value) {
            addCriterion("has_log <=", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogLike(String value) {
            addCriterion("has_log like", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogNotLike(String value) {
            addCriterion("has_log not like", value, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogIn(List<String> values) {
            addCriterion("has_log in", values, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogNotIn(List<String> values) {
            addCriterion("has_log not in", values, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogBetween(String value1, String value2) {
            addCriterion("has_log between", value1, value2, "hasLog");
            return (Criteria) this;
        }

        public Criteria andHasLogNotBetween(String value1, String value2) {
            addCriterion("has_log not between", value1, value2, "hasLog");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusIsNull() {
            addCriterion("collected_bonus is null");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusIsNotNull() {
            addCriterion("collected_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusEqualTo(Integer value) {
            addCriterion("collected_bonus =", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusNotEqualTo(Integer value) {
            addCriterion("collected_bonus <>", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusGreaterThan(Integer value) {
            addCriterion("collected_bonus >", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("collected_bonus >=", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusLessThan(Integer value) {
            addCriterion("collected_bonus <", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusLessThanOrEqualTo(Integer value) {
            addCriterion("collected_bonus <=", value, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusIn(List<Integer> values) {
            addCriterion("collected_bonus in", values, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusNotIn(List<Integer> values) {
            addCriterion("collected_bonus not in", values, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusBetween(Integer value1, Integer value2) {
            addCriterion("collected_bonus between", value1, value2, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andCollectedBonusNotBetween(Integer value1, Integer value2) {
            addCriterion("collected_bonus not between", value1, value2, "collectedBonus");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountIsNull() {
            addCriterion("actual_daily_count is null");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountIsNotNull() {
            addCriterion("actual_daily_count is not null");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountEqualTo(Integer value) {
            addCriterion("actual_daily_count =", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountNotEqualTo(Integer value) {
            addCriterion("actual_daily_count <>", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountGreaterThan(Integer value) {
            addCriterion("actual_daily_count >", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_daily_count >=", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountLessThan(Integer value) {
            addCriterion("actual_daily_count <", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountLessThanOrEqualTo(Integer value) {
            addCriterion("actual_daily_count <=", value, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountIn(List<Integer> values) {
            addCriterion("actual_daily_count in", values, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountNotIn(List<Integer> values) {
            addCriterion("actual_daily_count not in", values, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountBetween(Integer value1, Integer value2) {
            addCriterion("actual_daily_count between", value1, value2, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andActualDailyCountNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_daily_count not between", value1, value2, "actualDailyCount");
            return (Criteria) this;
        }

        public Criteria andClockinDateIsNull() {
            addCriterion("clockin_date is null");
            return (Criteria) this;
        }

        public Criteria andClockinDateIsNotNull() {
            addCriterion("clockin_date is not null");
            return (Criteria) this;
        }

        public Criteria andClockinDateEqualTo(String value) {
            addCriterion("clockin_date =", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateNotEqualTo(String value) {
            addCriterion("clockin_date <>", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateGreaterThan(String value) {
            addCriterion("clockin_date >", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateGreaterThanOrEqualTo(String value) {
            addCriterion("clockin_date >=", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateLessThan(String value) {
            addCriterion("clockin_date <", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateLessThanOrEqualTo(String value) {
            addCriterion("clockin_date <=", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateLike(String value) {
            addCriterion("clockin_date like", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateNotLike(String value) {
            addCriterion("clockin_date not like", value, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateIn(List<String> values) {
            addCriterion("clockin_date in", values, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateNotIn(List<String> values) {
            addCriterion("clockin_date not in", values, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateBetween(String value1, String value2) {
            addCriterion("clockin_date between", value1, value2, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andClockinDateNotBetween(String value1, String value2) {
            addCriterion("clockin_date not between", value1, value2, "clockinDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateIsNull() {
            addCriterion("serial_start_date is null");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateIsNotNull() {
            addCriterion("serial_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateEqualTo(String value) {
            addCriterion("serial_start_date =", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateNotEqualTo(String value) {
            addCriterion("serial_start_date <>", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateGreaterThan(String value) {
            addCriterion("serial_start_date >", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("serial_start_date >=", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateLessThan(String value) {
            addCriterion("serial_start_date <", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateLessThanOrEqualTo(String value) {
            addCriterion("serial_start_date <=", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateLike(String value) {
            addCriterion("serial_start_date like", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateNotLike(String value) {
            addCriterion("serial_start_date not like", value, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateIn(List<String> values) {
            addCriterion("serial_start_date in", values, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateNotIn(List<String> values) {
            addCriterion("serial_start_date not in", values, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateBetween(String value1, String value2) {
            addCriterion("serial_start_date between", value1, value2, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andSerialStartDateNotBetween(String value1, String value2) {
            addCriterion("serial_start_date not between", value1, value2, "serialStartDate");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayIsNull() {
            addCriterion("not_do_today is null");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayIsNotNull() {
            addCriterion("not_do_today is not null");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayEqualTo(String value) {
            addCriterion("not_do_today =", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayNotEqualTo(String value) {
            addCriterion("not_do_today <>", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayGreaterThan(String value) {
            addCriterion("not_do_today >", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayGreaterThanOrEqualTo(String value) {
            addCriterion("not_do_today >=", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayLessThan(String value) {
            addCriterion("not_do_today <", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayLessThanOrEqualTo(String value) {
            addCriterion("not_do_today <=", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayLike(String value) {
            addCriterion("not_do_today like", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayNotLike(String value) {
            addCriterion("not_do_today not like", value, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayIn(List<String> values) {
            addCriterion("not_do_today in", values, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayNotIn(List<String> values) {
            addCriterion("not_do_today not in", values, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayBetween(String value1, String value2) {
            addCriterion("not_do_today between", value1, value2, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andNotDoTodayNotBetween(String value1, String value2) {
            addCriterion("not_do_today not between", value1, value2, "notDoToday");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 09 17:35:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}