package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppHabitTemplateTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.id
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.name
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.min_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private Integer minValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.max_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private Integer maxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.creator
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.gmt_create
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.modifier
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.gmt_modified
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_template_tag.is_deleted
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.id
     *
     * @return the value of hab_app_habit_template_tag.id
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.id
     *
     * @param id the value for hab_app_habit_template_tag.id
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.name
     *
     * @return the value of hab_app_habit_template_tag.name
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.name
     *
     * @param name the value for hab_app_habit_template_tag.name
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.min_value
     *
     * @return the value of hab_app_habit_template_tag.min_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public Integer getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.min_value
     *
     * @param minValue the value for hab_app_habit_template_tag.min_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setMinValue(Integer minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.max_value
     *
     * @return the value of hab_app_habit_template_tag.max_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public Integer getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.max_value
     *
     * @param maxValue the value for hab_app_habit_template_tag.max_value
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setMaxValue(Integer maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.creator
     *
     * @return the value of hab_app_habit_template_tag.creator
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.creator
     *
     * @param creator the value for hab_app_habit_template_tag.creator
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.gmt_create
     *
     * @return the value of hab_app_habit_template_tag.gmt_create
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.gmt_create
     *
     * @param gmtCreate the value for hab_app_habit_template_tag.gmt_create
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.modifier
     *
     * @return the value of hab_app_habit_template_tag.modifier
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.modifier
     *
     * @param modifier the value for hab_app_habit_template_tag.modifier
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.gmt_modified
     *
     * @return the value of hab_app_habit_template_tag.gmt_modified
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.gmt_modified
     *
     * @param gmtModified the value for hab_app_habit_template_tag.gmt_modified
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_template_tag.is_deleted
     *
     * @return the value of hab_app_habit_template_tag.is_deleted
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_template_tag.is_deleted
     *
     * @param isDeleted the value for hab_app_habit_template_tag.is_deleted
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}