package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppHabitBgm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.id
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.name
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.bgm_order
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private Integer bgmOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.url
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.creator
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.gmt_create
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.modifier
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.gmt_modified
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_habit_bgm.is_deleted
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.id
     *
     * @return the value of hab_app_habit_bgm.id
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.id
     *
     * @param id the value for hab_app_habit_bgm.id
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.name
     *
     * @return the value of hab_app_habit_bgm.name
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.name
     *
     * @param name the value for hab_app_habit_bgm.name
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.bgm_order
     *
     * @return the value of hab_app_habit_bgm.bgm_order
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public Integer getBgmOrder() {
        return bgmOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.bgm_order
     *
     * @param bgmOrder the value for hab_app_habit_bgm.bgm_order
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setBgmOrder(Integer bgmOrder) {
        this.bgmOrder = bgmOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.url
     *
     * @return the value of hab_app_habit_bgm.url
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.url
     *
     * @param url the value for hab_app_habit_bgm.url
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.creator
     *
     * @return the value of hab_app_habit_bgm.creator
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.creator
     *
     * @param creator the value for hab_app_habit_bgm.creator
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.gmt_create
     *
     * @return the value of hab_app_habit_bgm.gmt_create
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.gmt_create
     *
     * @param gmtCreate the value for hab_app_habit_bgm.gmt_create
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.modifier
     *
     * @return the value of hab_app_habit_bgm.modifier
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.modifier
     *
     * @param modifier the value for hab_app_habit_bgm.modifier
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.gmt_modified
     *
     * @return the value of hab_app_habit_bgm.gmt_modified
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.gmt_modified
     *
     * @param gmtModified the value for hab_app_habit_bgm.gmt_modified
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_habit_bgm.is_deleted
     *
     * @return the value of hab_app_habit_bgm.is_deleted
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_habit_bgm.is_deleted
     *
     * @param isDeleted the value for hab_app_habit_bgm.is_deleted
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}