package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppFamilyMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.family_id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Long familyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.name
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.sex
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.avatar
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.birth_day
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.role
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Integer bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.collect_bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Integer collectBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.is_child
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String isChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.version
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.creator
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.gmt_create
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.modifier
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.gmt_modified
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_family_member.is_deleted
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.id
     *
     * @return the value of hab_app_family_member.id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.id
     *
     * @param id the value for hab_app_family_member.id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.family_id
     *
     * @return the value of hab_app_family_member.family_id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Long getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.family_id
     *
     * @param familyId the value for hab_app_family_member.family_id
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setFamilyId(Long familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.name
     *
     * @return the value of hab_app_family_member.name
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.name
     *
     * @param name the value for hab_app_family_member.name
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.sex
     *
     * @return the value of hab_app_family_member.sex
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.sex
     *
     * @param sex the value for hab_app_family_member.sex
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.avatar
     *
     * @return the value of hab_app_family_member.avatar
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.avatar
     *
     * @param avatar the value for hab_app_family_member.avatar
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.birth_day
     *
     * @return the value of hab_app_family_member.birth_day
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.birth_day
     *
     * @param birthDay the value for hab_app_family_member.birth_day
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.role
     *
     * @return the value of hab_app_family_member.role
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.role
     *
     * @param role the value for hab_app_family_member.role
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.bonus
     *
     * @return the value of hab_app_family_member.bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.bonus
     *
     * @param bonus the value for hab_app_family_member.bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.collect_bonus
     *
     * @return the value of hab_app_family_member.collect_bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Integer getCollectBonus() {
        return collectBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.collect_bonus
     *
     * @param collectBonus the value for hab_app_family_member.collect_bonus
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setCollectBonus(Integer collectBonus) {
        this.collectBonus = collectBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.is_child
     *
     * @return the value of hab_app_family_member.is_child
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getIsChild() {
        return isChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.is_child
     *
     * @param isChild the value for hab_app_family_member.is_child
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setIsChild(String isChild) {
        this.isChild = isChild == null ? null : isChild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.version
     *
     * @return the value of hab_app_family_member.version
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.version
     *
     * @param version the value for hab_app_family_member.version
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.creator
     *
     * @return the value of hab_app_family_member.creator
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.creator
     *
     * @param creator the value for hab_app_family_member.creator
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.gmt_create
     *
     * @return the value of hab_app_family_member.gmt_create
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.gmt_create
     *
     * @param gmtCreate the value for hab_app_family_member.gmt_create
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.modifier
     *
     * @return the value of hab_app_family_member.modifier
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.modifier
     *
     * @param modifier the value for hab_app_family_member.modifier
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.gmt_modified
     *
     * @return the value of hab_app_family_member.gmt_modified
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.gmt_modified
     *
     * @param gmtModified the value for hab_app_family_member.gmt_modified
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_family_member.is_deleted
     *
     * @return the value of hab_app_family_member.is_deleted
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_family_member.is_deleted
     *
     * @param isDeleted the value for hab_app_family_member.is_deleted
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}