package com.letsup.habit.app.backend.dao.entity;

import java.util.Date;

public class HabAppRoleUserRe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.role_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.user_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.creator
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.gmt_create
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.modifier
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.gmt_modified
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hab_app_role_user_re.is_deleted
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.id
     *
     * @return the value of hab_app_role_user_re.id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.id
     *
     * @param id the value for hab_app_role_user_re.id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.role_id
     *
     * @return the value of hab_app_role_user_re.role_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.role_id
     *
     * @param roleId the value for hab_app_role_user_re.role_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.user_id
     *
     * @return the value of hab_app_role_user_re.user_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.user_id
     *
     * @param userId the value for hab_app_role_user_re.user_id
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.creator
     *
     * @return the value of hab_app_role_user_re.creator
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.creator
     *
     * @param creator the value for hab_app_role_user_re.creator
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.gmt_create
     *
     * @return the value of hab_app_role_user_re.gmt_create
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.gmt_create
     *
     * @param gmtCreate the value for hab_app_role_user_re.gmt_create
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.modifier
     *
     * @return the value of hab_app_role_user_re.modifier
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.modifier
     *
     * @param modifier the value for hab_app_role_user_re.modifier
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.gmt_modified
     *
     * @return the value of hab_app_role_user_re.gmt_modified
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.gmt_modified
     *
     * @param gmtModified the value for hab_app_role_user_re.gmt_modified
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hab_app_role_user_re.is_deleted
     *
     * @return the value of hab_app_role_user_re.is_deleted
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hab_app_role_user_re.is_deleted
     *
     * @param isDeleted the value for hab_app_role_user_re.is_deleted
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}