spring:
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
server:
  port: 8001
mybatis:
    type-aliases-package: com.letsup.habit.app.backend.dao.entity
    mapper-locations: classpath:mappers/*.xml
logging:
  config: classpath:logback-spring.xml
# 打包   mvn -Dpackage.password=qtbigdata2019 clean package 启动java -jar encrypted-lng-management.jar