package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitTemplateTag;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitTemplateTagExample;
import java.util.List;

public interface HabAppHabitTemplateTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int countByExample(HabAppHabitTemplateTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitTemplateTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int insertSelective(HabAppHabitTemplateTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    List<HabAppHabitTemplateTag> selectByExample(HabAppHabitTemplateTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    HabAppHabitTemplateTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template_tag
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitTemplateTag record);
}