package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitLog;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitLogExample;
import java.util.List;

public interface HabAppHabitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    int countByExample(HabAppHabitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    int insertSelective(HabAppHabitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    List<HabAppHabitLog> selectByExample(HabAppHabitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    HabAppHabitLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_log
     *
     * @mbggenerated Tue Dec 03 11:13:00 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitLog record);
}