package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitIcon;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitIconExample;
import java.util.List;

public interface HabAppHabitIconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    int countByExample(HabAppHabitIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    int insertSelective(HabAppHabitIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    List<HabAppHabitIcon> selectByExample(HabAppHabitIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    HabAppHabitIcon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_icon
     *
     * @mbggenerated Fri Nov 22 11:37:52 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitIcon record);
}