package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitClass;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitClassExample;
import java.util.List;

public interface HabAppHabitClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    int countByExample(HabAppHabitClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    int insertSelective(HabAppHabitClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    List<HabAppHabitClass> selectByExample(HabAppHabitClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    HabAppHabitClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_class
     *
     * @mbggenerated Fri Nov 22 14:05:48 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitClass record);
}