package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitClockinRecord;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitClockinRecordExample;
import java.util.List;

public interface HabAppHabitClockinRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    int countByExample(HabAppHabitClockinRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitClockinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    int insertSelective(HabAppHabitClockinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    List<HabAppHabitClockinRecord> selectByExample(HabAppHabitClockinRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    HabAppHabitClockinRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_clockin_record
     *
     * @mbggenerated Wed Nov 27 13:37:22 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitClockinRecord record);
}