package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppUser;
import com.letsup.habit.app.backend.dao.entity.HabAppUserExample;
import java.util.List;

public interface HabAppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    int countByExample(HabAppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    int deleteByPrimaryKey(HabAppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    int insertSelective(HabAppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    List<HabAppUser> selectByExample(HabAppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    HabAppUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_user
     *
     * @mbggenerated Thu Nov 21 18:25:41 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppUser record);
}