package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppFamilyMember;
import com.letsup.habit.app.backend.dao.entity.HabAppFamilyMemberExample;
import java.util.List;

public interface HabAppFamilyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    int countByExample(HabAppFamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    int deleteByPrimaryKey(HabAppFamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    int insertSelective(HabAppFamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    List<HabAppFamilyMember> selectByExample(HabAppFamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    HabAppFamilyMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_family_member
     *
     * @mbggenerated Mon Dec 02 15:02:27 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppFamilyMember record);
}