package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppTemplateTagRe;
import com.letsup.habit.app.backend.dao.entity.HabAppTemplateTagReExample;
import java.util.List;

public interface HabAppTemplateTagReMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int countByExample(HabAppTemplateTagReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int deleteByPrimaryKey(HabAppTemplateTagRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int insertSelective(HabAppTemplateTagRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    List<HabAppTemplateTagRe> selectByExample(HabAppTemplateTagReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    HabAppTemplateTagRe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_template_tag_re
     *
     * @mbggenerated Fri Dec 20 11:57:14 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppTemplateTagRe record);
}