package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitColor;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitColorExample;
import java.util.List;

public interface HabAppHabitColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    int countByExample(HabAppHabitColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    int insertSelective(HabAppHabitColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    List<HabAppHabitColor> selectByExample(HabAppHabitColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    HabAppHabitColor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_color
     *
     * @mbggenerated Fri Nov 22 15:24:41 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitColor record);
}