package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabit;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitExample;
import java.util.List;

public interface HabAppHabitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    int countByExample(HabAppHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    int insertSelective(HabAppHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    List<HabAppHabit> selectByExample(HabAppHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    HabAppHabit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit
     *
     * @mbggenerated Thu Nov 28 16:18:58 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabit record);
}