package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppRoleUserRe;
import com.letsup.habit.app.backend.dao.entity.HabAppRoleUserReExample;
import java.util.List;

public interface HabAppRoleUserReMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    int countByExample(HabAppRoleUserReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    int deleteByPrimaryKey(HabAppRoleUserRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    int insertSelective(HabAppRoleUserRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    List<HabAppRoleUserRe> selectByExample(HabAppRoleUserReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    HabAppRoleUserRe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_role_user_re
     *
     * @mbggenerated Mon Nov 11 16:54:27 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppRoleUserRe record);
}