package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitTemplate;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitTemplateExample;
import java.util.List;

public interface HabAppHabitTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    int countByExample(HabAppHabitTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    int insertSelective(HabAppHabitTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    List<HabAppHabitTemplate> selectByExample(HabAppHabitTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    HabAppHabitTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_template
     *
     * @mbggenerated Thu Nov 28 09:43:33 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitTemplate record);
}