package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitBgm;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitBgmExample;
import java.util.List;

public interface HabAppHabitBgmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    int countByExample(HabAppHabitBgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitBgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    int insertSelective(HabAppHabitBgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    List<HabAppHabitBgm> selectByExample(HabAppHabitBgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    HabAppHabitBgm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_bgm
     *
     * @mbggenerated Fri Nov 29 10:55:28 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitBgm record);
}