package com.letsup.habit.app.backend.dao.mapper;

import com.letsup.habit.app.backend.dao.entity.HabAppHabitDailyRecord;
import com.letsup.habit.app.backend.dao.entity.HabAppHabitDailyRecordExample;
import java.util.List;

public interface HabAppHabitDailyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    int countByExample(HabAppHabitDailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    int deleteByPrimaryKey(HabAppHabitDailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    int insertSelective(HabAppHabitDailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    List<HabAppHabitDailyRecord> selectByExample(HabAppHabitDailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    HabAppHabitDailyRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hab_app_habit_daily_record
     *
     * @mbggenerated Mon Dec 09 17:35:19 CST 2019
     */
    int updateByPrimaryKeySelective(HabAppHabitDailyRecord record);
}